name: Ada with Alire

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Toolchain
      uses: ada-actions/toolchain@ce2021

    - name: Setup Alire
      uses: alire-project/setup-alire@v1

    - name: Build
      run: alr build

    - name: Test
      run: alr run test
