name: Ada (GNAT)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Alire
      uses: alire-project/setup-alire@v1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update && 
        sudo apt-get install gnat gprbuild

    - name: Build
      run: alr build
